# Usando python para resolver problemas de quântica

O objetivo deste notebook é oferecer uma visão geral de como podemos usar programação para resolver problemas de quântica de forma mais precisa e rápida do que usando lápis e papel, tornando o processo de aprendizagem mais dinâmico e agradável, além de acostumar o leitor à forma de trabalho que efetivamente é adotada por pesquisadores, afinal o processo de solução manual de problemas é propenso a erros, ao passo que a solução automatizada, através do uso de pacotes e bbibliotecas bem estabelecidas, é mais robusto e confiável (desde de que devidamente testado, claro). É importante ressaltar que este arquivo não objetiva introduzir a forma mais eficiente ou adequada de resolver os problemas, o que buscamos aqui é uma forma intuitiva de resolvê-los usando apenas o pacote ```numpy```.

Inicamos importando o pacote ```numpy```, o qual, para nosso conforto, rerrotulamos como ```np```:

In [5]:
import numpy as np
# este pacote pode ser intalado com o comando: pip install numpy 

O termo ```np``` agora será um _alias_ para ```numpy```, ou seja, sempre que o interprete vai substituir o em seu vocabulário a palavra ```numpy``` pela palavra ```np```, a primeira perdendo seu significado.

O pacote ```numpy``` introduz um objeto, gerado através do comando ```numpy.array()``` (ou, considerando o nosso alias, ```np.array()```), que possui as mesmas caracteristicas de uma matriz. Isso, somado ao fato de que python possui um suporte nato para numeros complexos, faz com que a abordagem apresentada aqui seja bastante amigável à solução dos problemas que costumamos ver nos cursos introdutórios (e avançados também!) de quântica.

Ademais, o ```numpy``` também inclui uma grande quantidade de ferramentas matemáticas que tornam nossa vida bastante fácil.

Vamos usar o fato de que estados quanticos puros admitem uma representação matricial na forma de um vetor e, consequentemente que os operadores lineares que atuam nestes vetores podem ser representados como matrizes para começar a explorar essa ferramenta. Inicialmente, nosso foco será um único sistema cujo espaço de estados possui dimensão 2, ou seja, um __qubit__.

Considere o operador $S_z$ e os estados $|0\rangle$ e $|1\rangle$ tais que:
  $$\begin{align}S_z|0\rangle & = |0\rangle\\ S_z|1\rangle & = -|1\rangle\end{align}$$
Vamos definir,
$$|0\rangle =\begin{bmatrix}1 \\ 0\end{bmatrix}\;\;\;\;\;\;\;\;\;\;|1\rangle =\begin{bmatrix}0 \\ 1\end{bmatrix}$$
e logo, temos que:
$$S_z = \begin{bmatrix}1 & 0\\ 0 & -1\end{bmatrix}$$

Através do ```numpy```, podemos representar esses estados e operador da seguinte forma:

In [14]:
ket_0 = np.array([[1],[0]])
ket_1 = np.array([[0],[1]])

sz = np.array([[1,0],[0,-1]])

Vamos visualizar as variáveis acima para verificar que estão de acordo com o esperado:

In [17]:
print(ket_0)
print(ket_1)
print(sz)

[[1]
 [0]]
[[0]
 [1]]
[[ 1  0]
 [ 0 -1]]


A partir disso, podemos representar outros estados, como por exemplo os auto-estados do operador $S_x$,
$$\begin{align}|+_x\rangle & = \frac{1}{\sqrt{2}}(|0\rangle + |1\rangle)\\ |-_x\rangle & = \frac{1}{\sqrt{2}}(|0\rangle - |1\rangle)\end{align}$$
que ficarão da seguinte forma:

In [19]:
plus_x = (ket_0 + ket_1)/np.sqrt(2)
minus_x = (ket_0 - ket_1)/np.sqrt(2)

Novamente, vamos visualizar o resultado acima:

In [21]:
print(plus_x)
print(minus_x)

[[0.70710678]
 [0.70710678]]
[[ 0.70710678]
 [-0.70710678]]


Uma operação fundamental em quântica é o conjugado do transposto de um estado ou operador. De fato, essa operação que normalmente representamos através do simbolo $\dagger$, conecta o estado (_ket_) com seu dual (_bra_), de um modo geral:
$$\langle \psi| = |\psi\rangle^{\dagger}$$

Para lidar com esse caso, podemos definir uma função:

In [37]:
def dagger(A):
    """Essa função aceita um ndarray e retorna o conjugado do transposto.
    ATENÇÃO!!! Certifique-se que o input tem dimensão 2, caso 
    contrário a operação de transposição não vai funcionar."""
    return np.transpose(np.conjugate(A))

Em posse dessa operação podemos, por exemplo, usar a decomposição espectral para escrever o operador $S_x$ em termos dos seus auto estados definidos anteriormente. Nesse caso, temos que:
$$S_x = |+_x\rangle\langle +_x| - |-_x\rangle\langle -_x|$$

Usando a função que definimos acima, definimos $S_x$ fica:

In [48]:
sx = np.matmul(plus_x,dagger(plus_x)) - np.matmul(minus_x,dagger(minus_x))

Vamos vizualizar o resultado:

In [47]:
print(sx)

[[0. 1.]
 [1. 0.]]


Por fim, podemos usar a função ```numpy.linalg.eig()``` para encontrar os autoestados associados com um operador uma vez que tenhamos em mãos sua representação matricial, bem como seus autovalores. Para exemplificar, vamos usar o operador $S_y$ cuja representação matricial é dada por:
$$S_y\begin{bmatrix}0 & -i\\ i & 0\end{bmatrix}$$
Vamos ver como essas fnções funcionam:

In [65]:
sy = np.array([[0,-1j],[1j,0]])
print(sy)
results = np.linalg.eig(sy)

[[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]]


Vamos vizualizar esses resultados.

Essa função retorna uma sequência. O primeiro objeto é um ndarray cujas entradas são os autovalores do operador que entramos como argumento da função. O segundo objeto, também um ndarray, contem uma sequência com os autoestados do operador na mesma ordem que os autovalores.

In [73]:
print("Rerultado geral:")
print(np.linalg.eig(sy))
print("\nSequência de autovalores:")
print(np.linalg.eig(sy)[0])
print("\nSequência de autoestados:")
print(np.linalg.eig(sy)[1])

Rerultado geral:
EigResult(eigenvalues=array([ 1.+0.j, -1.+0.j]), eigenvectors=array([[-0.        -0.70710678j,  0.70710678+0.j        ],
       [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

Sequência de autovalores:
[ 1.+0.j -1.+0.j]

Sequência de autoestados:
[[-0.        -0.70710678j  0.70710678+0.j        ]
 [ 0.70710678+0.j          0.        -0.70710678j]]


## Sistemas compostos

Quando trabalhamos com sistemas compostos, duas operações são cruciais:
- Produto tensorial
- Traço parcial

Vamos abordar cada um destes pontos individualmente.

### Produto tensorial

Para implementar o produto tensorial, que normalmente representamos através do simbolo $\otimes$, entre dois estados ou dois operadores, podemos recorrer a função ```numpy.kron()```.

Por exemplo, podemos calcular os estados 
$$\begin{align}|00\rangle = |0\rangle\otimes|0\rangle\\ |01\rangle=|0\rangle\otimes|1\rangle\\ |10\rangle = |1\rangle\otimes|0\rangle\\ |11\rangle = |1\rangle\otimes|1\rangle\end{align}$$
da seguinte forma,

In [80]:
ket_00 = np.kron(ket_0,ket_0)
ket_01 = np.kron(ket_0,ket_1)
ket_10 = np.kron(ket_1,ket_0)
ket_11 = np.kron(ket_1,ket_1)

Visualizando o $|00\rangle$, por exemplo:

In [85]:
print(ket_00)

[[1]
 [0]
 [0]
 [0]]


Da mesma forma, podemos calcular o produto tensorial de operadores:

Exemplificamos calculando $S_z\otimes S_x$:

In [86]:
szosx = np.kron(sz,sx)

Vamos ver o resultado:

In [87]:
print(szosx)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0. -0. -1.]
 [ 0.  0. -1. -0.]]


### Traço parcial

Antes de prosseguirmos com o traço parcial, vale ressaltar que o traço total pode ser facilmente calculado através da função ```numpy.trace()```.

Para ilustrar, vamos primeiro definir o operador densidade $\rho$ associado ao autoestado do operador $S_x$ com autovalor positivo. Lembrando que:
$$\rho = |+_x\rangle\langle +_x|$$
Temos que,

In [89]:
rho = np.matmul(plus_x,dagger(plus_x))
print(rho)

[[0.5 0.5]
 [0.5 0.5]]


Agora, vamos verificar o traço:

In [90]:
print(np.trace(rho))

0.9999999999999998


Como um outro exemplo, podemos calcular o traço de $S_z$:

In [91]:
print(np.trace(sz))

0


# Exercício

Considere o seguinte experimento.

Um sistema composto por duas partes se encontra no estado $|\psi\rangle$, dado por
$$|\psi\rangle = \frac{1}{\sqrt{2}}(|01\rangle - |10\rangle)$$
É distribuído para dois experimentalistas, Alice e Bob que estão separados espacialmente.

Alice possui dois setups experimentais para medir o seu sistema, o setup $0$ e o setup $1$. Ela escolhe que setup vai usar de acordo com o resultado de uma variável aleatória $x$ que pode assumir os valores $0$ e $1$. O setup $0$ mede o observável $S_z$, e o setup $1$ mede o observável $S_x$, obtendo o resultado $a = 0$ se o autovalor $1$ for observado e $a = 1$, se observado o autovalor $-1$.

De forma análoga, Bob também possui dois setups rotulados como $0$ e $1$, e decide qual utilizar de acordo com uma variável $y$ obtendo o resultado $b$ que pode ser $0$ ou $1$ de acordo com os autovalores $1$ e $-1$ respectivamente. O setup associado à $y=0$ mede o observável $\frac{-S_z - S_x}{\sqrt{2}}$ e o assiciado à $y=1$ mede $\frac{S_z - S_x}{\sqrt{2}}$.

__Primeiro passo__ Calcule os autoestados de todos os observáveis envolvidos.

__Segundo passo__ Calcule os Projetores em todos os autoespaços de todos os observáveis envolvidos.

__Terceiro passo__ Calcule o produto tensorial de todos os pares de projetores de Alice e Bob.

__Quarto passo__ Use os resultados anteriores para calcular todos $16$ valores de $p(a,b|x,y)$.

__Quinto passo__ Use o resultado do item anterior para calcular $CHSH$, sendo:
$$CHSH = E_{00} + E_{01} + E_{10} - E_{11}$$
na qual
$$E_{xy} = \sum_{a,b}(-1)^{a+b}p(a,b|x,y)$$